version: '3.7'

services:
  saturnos:
    container_name: saturnos_bot
    build: .
    ports:
      - '${API_PORT}:3000'
    volumes:
      - .:/home/service
    depends_on:
      - database

  database:
    container_name: database_container
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/mongo

volumes:
  mongo_data:
